### ISSUE TITLE
Sales records of uplifter / hawker with no stockpoint

### ISSUE THREAD

**Issue by cypru55** [Reliefwatch/wrigley_guide#1]
![salesrecordswithnostockpoint](https://cloud.githubusercontent.com/assets/676519/13068451/6d62e9f6-d4b6-11e5-966a-70734f54edf9.png)

**Comment by dcyu** [comment]
@cypru55  This exists because some stockpoints were removed from the system. These uplifters will need to be reassigned to stockpoints.

**Comment by cypru55** [comment]
@dcyu I think the records might mixed up, so it takes kevin the uplifter?
see below.
![kevinochieng](https://cloud.githubusercontent.com/assets/676519/13132491/0abddaee-d62e-11e5-8878-1b87d66ed8e9.png)
