### ISSUE TITLE
Application Error when trying to download CSV file

### ISSUE THREAD

**Issue by cypru55** [Reliefwatch/wrigley_guide#20]
I encountered this problem when I tried to download csv file for sales data, but sometimes I can download too. Not sure what's the problem
![applicationerror](https://cloud.githubusercontent.com/assets/676519/13483317/339dae2a-e12e-11e5-8421-720cce5f8e89.png)

**Comment by dcyu** [comment]
Do you happen to know what month you were trying to download? I'm trying to replicate the error but am not able to do so.

**Comment by cypru55** [comment]
Hi Daniel, I tried to download sept, oct, nov, dec 2015 data, now I checked again it's fine..

**Comment by dcyu** [comment]
We do have error logs but I checked and did not see this error. Please let me know if it arises again.
