### ISSUE TITLE
Log problem

### ISSUE THREAD

**Issue by cypru55** [Reliefwatch/wrigley_guide#22]
All MOR mentioned they didn't make any changes to Jan-Feb 2016 data after 26 Feb 2016, but the logs showing differently

![logs](https://cloud.githubusercontent.com/assets/676519/13490288/a27e1cde-e166-11e5-95c6-b83220eebc92.png)

**Comment by dcyu** [comment]
This problem has been addressed by fixes and a reset to the logs.
