### ISSUE TITLE
Changes in Past Sales Records

### ISSUE THREAD

**Issue by cypru55** [Reliefwatch/wrigley_guide#23]
Different data showing since data downloaded from sokowatch mid of Jan, and Now.

![comparison](https://cloud.githubusercontent.com/assets/676519/13490413/51483fec-e167-11e5-87c5-ee6b5186d847.png)

**Comment by dcyu** [comment]
Likely the result of past data still being added by MOR's. @cypru55 please consult with Yan and Clara to decide if a cutoff should be implemented and how so. As much detail as possible would be appreciated.

**Comment by cypru55** [comment]
Hi Daniel, for this particular case, I think it's related to issue #24 where if there is same entrepreneur with 2 ids, you mentioned that you have deleted one of the ID and chose ID with more total bags sold. What happen to the sales made with the other ID?

Example in the spreadsheet for one Entrepreneur (Francis Mwangi Tonah)
[francismwangitonah.xlsx](https://github.com/Reliefwatch/wrigley_guide/files/160714/francismwangitonah.xlsx)


However to prevent any other modification to past data, it's logical for MOR not to edit past 2 mths data.

**Comment by dcyu** [comment]
The sales records of the old ID were reassigned to the new ID, so no data was lost.

**Comment by yan-catalyst** [comment]
Hi Dan, from the notes I took during our call last Friday (Mar 4th, 2016), we agreed system cut off would be 2 months (i.e, MOR will not be able to make change to data 2 months back) and access would be given to admin account for Lina to make changes to records, if needed.

**Comment by dcyu** [comment]
I have added new issues for the two month cutoff and admin level account to account for these requests.
