### ISSUE TITLE
Inconsistent ID found in sokowatch data downloaded in Jan vs March

### ISSUE THREAD

**Issue by cypru55** [Reliefwatch/wrigley_guide#24]
![inconsistent id](https://cloud.githubusercontent.com/assets/676519/13517431/7d3f68e0-e1fe-11e5-8851-d265f5045d60.png)

Data is in excel file, the yellow color tab is raw data for (Sept-Dec) downloaded in mid jan 2016 and 3 march 2016
[Uploading maua-data comparison.xlsx…]()

**Comment by dcyu** [comment]
As mentioned, this was due to duplicate records of entrepreneurs being removed from the system. I have done another review of entrepreneur records to remove duplicates that still remained within the system.
